# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Isotoma viridis
# List of path to Hi-C sequence files.
hic_sequence_files:
  read1:
    - /faststorage/project/EcoGenetics/BACKUP/genome_assembly_and_annotation/hic/Isotoma_viridis/IsoVir_Hi-C_L1_1.1.fq.gz
    - /faststorage/project/EcoGenetics/BACKUP/genome_assembly_and_annotation/hic/Isotoma_viridis/IsoVir_Hi-C_L1_1.2.fq.gz
  read2:
    - /faststorage/project/EcoGenetics/BACKUP/genome_assembly_and_annotation/hic/Isotoma_viridis/IsoVir_Hi-C_L1_2.1.fq.gz
    - /faststorage/project/EcoGenetics/BACKUP/genome_assembly_and_annotation/hic/Isotoma_viridis/IsoVir_Hi-C_L1_2.2.fq.gz
# Path to draft genome file.
draft_genome_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola/Isotoma_viridis/draft_assembly/purge_dups_primary/04/IsoVir.purged.fa
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola
# 3D-DNA settings.
input_size: 10000 # (Default 15000)
number_of_edit_rounds: 6 # (Default 2)
# Reviewed .assembly file generated from JuiceBox (can be left blank until a reviewed file has been produced).
reviewed_assembly_file: 
number_of_chromosomes_to_keep: 
# Name of BUSCO lineage dataset to use for analysis.
busco_dataset_name: arthropoda_odb10