# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Gonepteryx rhamni
# Genome assembly files to be masked
genome_assembly: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/museomics/Gonepteryx_rhamni/HiC_scaffolding/juicer/3ddna_in15000_r3/finalize/purged.nodebris.fasta
# Repetitive region database file:
repeat_database: 
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/museomics
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/museomics
