# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Orchesella villosa
# Path to genome assembly file.
genome_assembly_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola/Orchesella_villosa/repeatmasking/OrcVil.softmasked.fna
# List of path to RNA sequence files (read 1 & read 2)
rna_sequence_files:
- /faststorage/project/EcoGenetics/BACKUP/RNA_data/Orchesella_villosa/Ovil-RNA_R1_001.fastq.gz
- /faststorage/project/EcoGenetics/BACKUP/RNA_data/Orchesella_villosa/Ovil-RNA_R2_001.fastq.gz
# Directory for intermediary files.
working_directory_path: 
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola
