# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Entomobrya nicoleti
# List of path to Hi-C sequence files.
hic_sequence_files:
- /faststorage/project/EcoGenetics/BACKUP/HiC/EntNic/Ent_Nic_L1_1.fq.gz
- /faststorage/project/EcoGenetics/BACKUP/HiC/EntNic/Ent_Nic_L1_2.fq.gz
# Path to draft genome file.
draft_genome_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/data/EntNic_HiFi/mixed99/hifiasm/purge_dups/04/purged.fa
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola
# 3D-DNA settings.
input_size: 10000 # (Default 15000)
number_of_edit_rounds: 6 # (Default 2)
