# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Lepidocyrtus lignorum
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/collembola
# Path to PacBio sequence file.
pacbio_hifi_sequence_files:
  - /faststorage/project/EcoGenetics/BACKUP/PacBio_HiFi/Lepidocyrtus_lignorum/LELA_m64101e_221212_121647.hifi_reads.fastq.gz
# Use Hi-C data during assembly? (1 = Yes/2 = No/3 = Both).
use_hic_data: 3
# List of Hi-C sequence files if avalable (optional).
hic_sequence_files:
  - 
# Name of BUSCO lineage dataset to use for analysis.
busco_dataset_name: arthropoda_odb10
# Number of purge_dups rounds.
purge_dups_rounds: 4