# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Bathyphantes gracilis
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/spiders
# Path to PacBio sequence file.
pacbio_hifi_sequence_files:
  - /faststorage/project/EcoGenetics/BACKUP/PacBio_HiFi/Bathyphantes_gracilis/BatGra_m64101e_231210_143645.bc1009--bc1009.hifi_reads.fastq.gz
  - /faststorage/project/EcoGenetics/BACKUP/PacBio_HiFi/Bathyphantes_gracilis/BatGra_m64101e_240219_135040.hifi_reads.bc1009--bc1009.fastq.gz
  - /faststorage/project/EcoGenetics/BACKUP/PacBio_HiFi/Bathyphantes_gracilis/BatGra_m64101e_240223_114600.hifi_reads.bc1009--bc1009.fastq.gz
# Use Hi-C data during assembly? (1 = Yes/2 = No/3 = Both).
use_hic_data: 1
# List of Hi-C sequence files if avalable (optional).
hic_sequence_files:
  - /faststorage/project/EcoGenetics/BACKUP/HiC/BatGra/Bagr_L1_1.fq.gz
  - /faststorage/project/EcoGenetics/BACKUP/HiC/BatGra/Bagr_L1_2.fq.gz
# Name of BUSCO lineage dataset to use for analysis.
busco_dataset_name: arachnida_odb10
# Number of purge_dups rounds.
purge_dups_rounds: 4
