# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Apion virens
# Directory for intermediary files.
working_directory_path: 
# Directory for final output files.
output_directory_path: 
