# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Apion virens
# Directory for final output files.
output_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/genome_assembly_and_annotation/steps/beetles
# Path to PacBio sequence file.
pacbio_hifi_sequence_file: /faststorage/project/EcoGenetics/BACKUP/PacBio_HiFi/Apion_virens/ApiVir44A_m84108_230831_160317_s4.hifi_reads.bc1001.fastq.gz
# List of Hi-C sequence files if avalable (optional).
hic_sequence_files:
- /faststorage/project/EcoGenetics/BACKUP/HiC/ApiVir/API_VIR_L1_1.fq.gz
- /faststorage/project/EcoGenetics/BACKUP/HiC/ApiVir/API_VIR_L1_2.fq.gz
# Name of BUSCO lineage dataset to use for analysis.
busco_dataset_name: endopterygota_odb10
# Number of purge_dups rounds.
purge_dups_rounds: 4
